import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Layout from "../component/layout";
import { NavLocation } from '../models/nav_location';

export default function Home() {
  return (
    <Layout location={NavLocation.Home}>
      <Head>
        <title>Durid's Portfolio - Home Page</title>
        {/** TODO: Fix link card */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.intro}>
          <div className={styles.bottomSlant}></div>
          <div className={styles.content}>This is the content</div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </Layout>
  )
}
