import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Layout from "../component/layout";
import { NavLocation } from '../models/nav_location';

export default function Home() {
  return (
    <Layout location={NavLocation.Home}>
      <Head>
        <title>Durid&apos;s Portfolio - Home Page</title>
        {/** TODO: Fix link card */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.introWrapper}>
          <div className={styles.intro}>
            <div className={styles.content}>
              <div className={styles.paragraph}>
                <h1>Hi! My name's DURID AHMAD</h1>
                <p>
                  I am a <span className={styles.focus}>Software Engineer</span> who loves to learn how different technologies work. 
                  I am capable of adapting to challenges and working with the resources I have. 
                  My favorite part of software development is understanding how data-intensive applications are built, 
                  and how to properly store that data.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      {/** TODO: Maybe add a footer? */}
      </footer>
    </Layout>
  )
}
